### ISSUE TITLE
Weird chart rendering behaviour on clean cache

### ISSUE THREAD

**Issue by mrchrisadams** [climateaction-tech/branch-theme#25]
In branch issue 3, I've had an issue reported with the image rendering, and I can now reproduce the issue myself.

## Steps to reproduce

Visit a page with a clean cache, when we have a the carbon intensity set to high. On first load, it looks like this:

<img width="1392" alt="Screenshot 2021-12-03 at 17 55 11" src="https://user-images.githubusercontent.com/17906/144642688-c7c1a004-f4d4-4e55-bc5f-9503a49418ff.png">

On the second load, it looks more like this - how we would like it to look:

<img width="1392" alt="Screenshot 2021-12-03 at 17 55 15" src="https://user-images.githubusercontent.com/17906/144642839-ee42e43f-03e0-430f-b61a-2562a175811a.png">

I'm able to reproduce this issue by reloading it with shift held down, which I think disables the cache, or at least loads without the cache enabled (I'm not 100% tho…)

I'm not sure why this happens - @jacklenox, any ideas?

**Comment by dubsnipe** [comment]
There's an inline style added to the span wrapping ```.carbon-alt``` that is set to ```width: 0px; height: 0px; display: inline-block;```. You could either replace that by ```visibility:hidden;``` or style it to go inline.

**Comment by jacklenox** [comment]
The problem appears to be that the image was coming from a remote Google URL, and hadn’t actually been uploaded to the site. I downloaded the image in question from Google and uploaded it as a replacement and all is now well.

**Comment by jacklenox** [comment]
@dubsnipe Sorry, I just realised I didn't address your question! It was some time ago now, but I believe the reason I didn't go the `visibility: hidden` route way back when (which would have saved a lot of bother) is because the browser still downloaded the images. This obviously undermines the point of the carbon aware/energy saving aspect of the design.

This is definitely something we'll revisit as we refactor some of the (admittedly horrible) code that does the heavy lifting here.

**Comment by mrchrisadams** [comment]
Thanks for clearing this up @jacklenox  - this makes total sense now, and I can see why it was acting the way it was before, and fix it by updating the references. Huzzah!
